### ISSUE TITLE
Unit tests for Hub controller

### ISSUE THREAD

**Issue by elevran** [axon-submariner/lighthouse#27]
determine if can run tests using a fake client for controller.Client (doable for generated MCS client...)

- [x] create export -> expect import
- [x] create 2 exports -> expect 2 imports
- [x] create export, then delete it -> expect import to be deleted as well (since there is no real API server. confirm finalizer cleared)
- [x] create and update export -> import unchanged (assumes none of the service properties changed)
- [x] create and update export's service specification -> updated import
- [x] create 2 exports that are in conflict -> expect condition conflict on one export and an import for the other

**Comment by itay-nakash** [comment]
**regarding test 2** -"create 2 exports -> expect 2 imports" :
Do you want to test the scenario that creates 2 exports and only then calls reconcile, or after each export should I call reconcile?
(as I understand, after each creation the reconcile will be called since it watches the export resource, however, maybe you want to test a scenario that the exports creating before the controller gets the update)

1. Create 2 exports using the client.Create
2. Calling Reconcil manually
3.  make sure it created 2 ServiceImports

OR

1. Create 1 export using the client.Create
2. Calling Reconcil manually
3. Creating another export
4. Calling Reconcil manually  **again**
5. make sure it created 2 ServiceImports

**regarding test 4**  - "create and update export -> import unchanged (assumes none of the service properties changed)" :
Do you have an example for a reasonable change in the export that shouldn't affect the import?

**Comment by elevran** [comment]
> regarding (2) 

you can (and should) preload both objects at once, but need to call reconcile for each separately (each time with a different key).
   There is no real "watch loop" that gets notified.
   
> (4)

  update the labels or annotations?

**Comment by itay-nakash** [comment]
> you can (and should) preload both objects at once, but need to call reconcile for each separately (each time with a different key).

I should Preload them to the client, and not use the Create function of the fake client?

**Comment by elevran** [comment]
Correct.
The set of preloaded objects represents the API server state. There is not real (active) server that responds to (for example) WATCH or garbage collect objects. It is more accurate to see this as way to create/read/update/delete objects from a memory store.
